/* eslint-disable require-jsdoc */
function getStatusDescription(statusCode) {
  const statusMap = {
    1: "AWB Assigned",
    2: "Label Generated",
    3: "Pickup Scheduled/Generated",
    4: "Pickup Queued",
    5: "Manifest Generated",
    6: "Shipped",
    7: "Delivered",
    8: "Cancelled",
    9: "RTO Initiated",
    10: "RTO Delivered",
    11: "Pending",
    12: "Lost",
    13: "Pickup Error",
    14: "RTO Acknowledged",
    15: "Pickup Rescheduled",
    16: "Cancellation Requested",
    17: "Out For Delivery",
    18: "In Transit",
    19: "Out For Pickup",
    20: "Pickup Exception",
    21: "Undelivered",
    22: "Delayed",
    23: "Partially Delivered",
    24: "Destroyed",
    25: "Damaged",
    26: "Fulfilled",
    38: "Reached at Destination",
    39: "Misrouted",
    40: "RTO NDR",
    41: "RTO OFD",
    42: "Picked Up",
    43: "Self Fulfilled",
    44: "DISPOSED_OFF",
    45: "CANCELLED_BEFORE_DISPATCHED",
    46: "RTO_IN_TRANSIT",
    47: "QC Failed",
    48: "Reached Warehouse",
    49: "Custom Cleared",
    50: "In Flight",
    51: "Handed over to Courier",
    52: "Shipment Booked",
    54: "In Transit Overseas",
    55: "Connected Aligned",
    56: "Reached Overseas Warehouse",
    57: "Custom cleared Overseas",
    59: "Box Packing",
    60: "FC Allocated",
    61: "Picklist Generated",
    62: "Ready to Pack",
    63: "Packed",
    67: "FC Manifest Generated",
    68: "Processed At Warehouse",
    71: "Hanover Exception",
    72: "Packed Exception",
    75: "RTO_LOCK",
    76: "UNTRACABLE",
    77: "ISSUE_RELATED_TO_THE_RECIPIENT",
    78: "REACHED_BACK_AT_SELLER_CITY",
  };
  return statusMap[statusCode] || "Unknown Status Code";
}

module.exports = getStatusDescription;

